debug: true
spring:
  cache:
    type: jcache
    jcache:      provider: com.hazelcast.cache.impl.HazelcastServerCachingProvider
  main:    allow-bean-definition-overriding: true
bucket4j:
  enabled: true
  filters:
  - cache-name: buckets
    url: .*
    rate-limits:
    - bandwidths:
      - capacity: 5
        time: 10
        unit: seconds