logging:
  level:
    com.giffing.bucket4j: debug
management:
  endpoints:
    web:
      exposure:
        include: "*"
  security:
    enabled: false
spring:
  cache:
    jcache:
      provider: com.github.benmanes.caffeine.jcache.spi.CaffeineCachingProvider
    cache-names:
    - buckets
    caffeine:
      spec: maximumSize=1000000,expireAfterAccess=3600s
bucket4j:
  enabled: true
  filters:
  - cache-name: buckets
    url: .*
    rate-limits:
    - cache-key: getRemoteAddr() 
      skip-predicates:
      - name: QUERY=ADMIN
      bandwidths:
      - capacity: 10
        refill-capacity: 1
        time: 1
        unit: seconds
        initial-capacity: 20
        refill-speed: interval
